name: VFSLite CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run disk tests
        run: go test ./disk -v

      - name: Run core and api tests
        run: go test -v